# configs/vae_fairness.yaml
experiment: vae
input_dim: 784
latent_dim: 16
encoder_layers: [512, 256, 128]
decoder_layers: [128, 256, 512]
activation: relu
loss_type: mse
lr: 0.001
epochs: 20
kl_weight: 0.001
save_dir: runs/vae_test


# paths
log_dir: /mnt/home/forebacj/CIR/logs/vae_experiment
